#wrote by null
#kys
#imma big booter haxxer man

import random, time, os

print('would you like to play rock paper scissors?')
print('the computer will pick a number 1-3.')
print('one being rock, two being paper, and three being scissprs.')
yon = input('yes or no?: ')

if yon == 'yes':
    rps = input('Ok then pick, Rock, Paper, or Scissors: ')
    os.system('cls')
    print('rock...')
    time.sleep(1)
    os.system('cls')
    print('paper...')
    time.sleep(1)
    os.system('cls')
    print('scissors...')
    time.sleep(1)
    os.system('cls')
    print('shoot!!!')
    time.sleep(.5)
    os.system('cls')
    number = random.randint(1, 3)
    print('the enemy has choosen', number)
    print ('you had selected', rps)
    time.sleep(3)

    print('would you like to play rock paper scissors?')
print('the computer will pick a number 1-3.')
print('one being rock, two being paper, and three being scissprs.')
yon = input('yes or no?: ')

if yon == 'yes':
    rps = input('Ok then pick, Rock, Paper, or Scissors: ')
    os.system('cls')
    print('rock...')
    time.sleep(1)
    os.system('cls')
    print('paper...')
    time.sleep(1)
    os.system('cls')
    print('scissors...')
    time.sleep(1)
    os.system('cls')
    print('shoot!!!')
    time.sleep(.5)
    os.system('cls')
    number = random.randint(1, 3)
    print('the enemy has choosen', number)
    print ('you had selected', rps)
    time.sleep(3)

    print('would you like to play rock paper scissors?')
print('the computer will pick a number 1-3.')
print('one being rock, two being paper, and three being scissprs.')
yon = input('yes or no?: ')

if yon == 'yes':
    rps = input('Ok then pick, Rock, Paper, or Scissors: ')
    os.system('cls')
    print('rock...')
    time.sleep(1)
    os.system('cls')
    print('paper...')
    time.sleep(1)
    os.system('cls')
    print('scissors...')
    time.sleep(1)
    os.system('cls')
    print('shoot!!!')
    time.sleep(.5)
    os.system('cls')
    number = random.randint(1, 3)
    print('the enemy has choosen', number)
    print ('you had selected', rps)
    time.sleep(3)